### ISSUE TITLE
Consider publish to npm registry

### ISSUE THREAD

**Issue by gcalmettes** [jlegewie/reveal.js-d3js-plugin#3]
Would you consider publishing reveal.js to npm?

This would allow `reveal.js-d3js-plugin` to be easily integrated into `reveal.js` boilerplate/templates solutions (e.g. [revealjs-template](https://github.com/flying-sheep/revealjs-template)).

Not much work is needed to be able to publish to npm, just add a `package.json` file to the repo (see for example the [`package.json` file](https://github.com/denehyg/reveal.js-menu/blob/master/package.json)) of the [`reveal.js-menu` plugin](https://github.com/denehyg/reveal.js-menu) that is also available on the [npm registry](https://www.npmjs.com/package/reveal.js-menu).

Thanks for considering this.

**Comment by jlegewie** [comment]
I am not going to invest a lot of time in this but I just added a `package.json` file. Does that look good? What else do I need to do?

**Comment by gcalmettes** [comment]
Thanks a lot @jlegewie!

If you're already a user of the npm registry (if you have a user login information already stored on your machine), then `npm publish` will do the work ;)

If not, there is only one additional step to do. Please see [this page](https://docs.npmjs.com/getting-started/publishing-npm-packages) where all the steps are described.

**Comment by jlegewie** [comment]
Done!

https://www.npmjs.com/package/reveal.js-d3js

**Comment by gcalmettes** [comment]
Thanks a lot!

**Comment by gcalmettes** [comment]
added instructions on how to install with npm in #4.
