### ISSUE TITLE
Support for data-fragment-index attribute

### ISSUE THREAD

**Issue by gcalmettes** [jlegewie/reveal.js-d3js-plugin#5]
Would you be open to break a bit the API to allow the support for the [`data-fragment-index`](https://github.com/hakimel/reveal.js/#fragments) attribute of the Reveal fragments?

If the `_transitions` array is an array of dictionaries instead of an array of functions to be triggered, this function can be supported if an `index` attribute (optional) is present, and the forward (`_transitions`) and backward (`_transitions_inverse`) (optional) transitions can also be merged in a single array:

```
var _transitions = [
  {transitionForward: () => { function to be called },
   index: 1, // OPTIONAL. index is zero based
   transitionBackward: () => { function to be called for the reversed transition} // OPTIONAL
  },
  {transitionForward: () => { function to be called },
   index: 3, // OPTIONAL. index is zero based
   transitionBackward: () => { function to be called for the reversed transition} // OPTIONAL
  },
  etc ...
]
```
I have made a working example, see [this demo](https://gcalmettes.github.io/reveal.js-d3js-plugin/demo/#/) for the resulting behavior.

The changes in the code can be viewed [here](https://github.com/gcalmettes/reveal.js-d3js-plugin/commit/9e5f6cc4e98bfadaf12dc44057202248676e93d5).

I can open a pull request if you think this could be useful.

**Comment by jlegewie** [comment]
Maybe I am missing something but I think you can already do that with the old API with the `fig-transition` class. Look at this example from the `demo/index.html` file:

```
<p class="fragment">
    No transition triggered
</p>
<p class="fragment fig-transition">
    First transition triggered
</p>
<p class="fragment">
    No transition triggered
</p>
<p class="fragment fig-transition">
    Second transition triggered
</p>
```

**Comment by gcalmettes** [comment]
@jlegewie I agree that you example works, but you have no way to control the `data-fragment-index` for simultaneous fragments transitions.

For example, what if you wanted two different DOM object to be triggered with the first transition? (see below).

```
<p class="fragment">
    No transition triggered
</p>
<p class="fragment fig-transition">
    First transition triggered
</p>
<p class="fragment fig-transition">
    Another paragraph to be triggered with first transition
</p>

<p class="fragment">
    No transition triggered
</p>
<p class="fragment fig-transition">
    Second transition triggered
</p>
```

**Comment by gcalmettes** [comment]
My bad, this works too :)

**Comment by gcalmettes** [comment]
Thanks for the great work @jlegewie!

My bad, I was not actually aware of the `fig-transition` class feature of the library ;)

You might want to mention it in the Readme, so people know that this plugin also supports selective triggering of transitions!

**Comment by jlegewie** [comment]
Just to explain how it works: You can create and structure all transitions yourself using `fragment fig-transition` (including indices etc). I just add empty elements with `fragment fig-transition` for the missing transitions add the end. So if you have 4 transitions in your d3.js vis and only two `fragment fig-transition` elements in your slide, I add two empty elements for the missing transitions with class `fragment fig-transition`. If you have 0 in your slide, I add all 4 as empty elements.

**Comment by gcalmettes** [comment]
Thanks for the clarification @jlegewie, I dug into the code and saw that.

My interest for support of the `data-fragment-index` syntax was also linked to the idea of being able to support multiple independent `D3` visualizations in a single slide, and have total control over the order the transitions are triggered for each of them (for example in the case one want to show the comparison of two versions of a visualization side by side, or show a difference in transition sequence). 

I modified the code a bit to support multiple visualizations on a single slide (see [demo here](https://gcalmettes.github.io/reveal.js-d3js-plugin/demo/#/3)), but with the current approach one's has to include blank transitions in the `_transitions` array to control asynchronous transitions.

I understand that your first objective while developing this plugin was to keep it as simple as possible and you might not need this feature or be interested in including this.
I'll work a bit more on that and show you what I come up with.

**Comment by gcalmettes** [comment]
The `data-fragment-index` support was way more tricky than I initially thought (especially to handle the sequence when several visualizations are on the slide), so I ended up rewriting a full plugin inspired by the work you had done. See the [demo](https://gcalmettes.github.io/reveal.js-d3/demo/) and [code](https://github.com/gcalmettes/reveal.js-d3/blob/master/reveald3.js).
